### PR TITLE
Add CPU percentage to result

### PR DESCRIPTION
**Pull request by SamVerschueren**
Adding the CPU percentage to the result set. Still have to find a workaround for Windows so it's work in progress right now.

If #5 is merged, I will rebase to master.

### CODE REVIEW

**Comment by sindresorhus** [comment]
@MarkTiedemann Do you know the best way to get the CPU percentage on Windows?

**Comment by MarkTiedemann** [comment]
@sindresorhus No, I honestly don't. (Been exploring some stuff, though, if anyone's interested: [gist](https://gist.github.com/MarkTiedemann/26f153dfd3f6a318bdd3c395a60650fa).)

**Comment by sindresorhus** [comment]
@SamVerschueren How about we just add a note about it not supporting Windows for now and open an issue about adding Windows support?

**Comment by SamVerschueren** [comment]
Yes good idea. Otherwise I don't feel like this PR can be merged any time soon.

**Comment by sindresorhus** [comment]
When you have time, can you add a note to the readme about not being supported on Windows?

**Comment by SamVerschueren** [comment]
Something like this?

**Comment by SamVerschueren** [comment]
Weird, no clue why it fails on AppVeyor...

**Comment by EmptyCrown** [comment]
Hey guys, any update on getting something similar to work on Windows?

**Pull request merged**
