### PR TITLE
CI updates

### PR DESCRIPTION
**Pull request by brandon93s**
Move Windows CI Build to Travis.

@sindresorhus if this is a favorable change, I am going to apply the same change to a [few others](https://github.com/search?p=1&q=user%3Asindresorhus+%22ci.appveyor.com%2Fproject%2Fsindresorhus%22&type=Code).

### CODE REVIEW

**Comment by sindresorhus** [comment]
Yup. Happy to switch out AppVeyor with Travis on other repos too.

**Comment by sindresorhus** [comment]
Note that I’m not interested in adding testing on Windows for repos that don’t already do that with AppVeyor.

**Comment by sindresorhus** [comment]
I think `os` should be first in the file.

**Comment by brandon93s** [comment]
> Note that I’m not interested in adding testing on Windows for repos that don’t already do that with AppVeyor.

+1 - just consolidating existing AppVeyor builds.

> I think os should be first in the file.

Done

**Pull request merged**
