### PR TITLE
more columns

### PR DESCRIPTION
**Pull request by dbkaplun**

### CODE REVIEW

**Comment by dbkaplun** [comment]
Hmm, looks like the added columns are causing `ARGS` to get truncated to 64 characters. Investigating.

**Comment by sindresorhus** [comment]
I don't think I want this. The point of this module was to make something that is the same on both Unix and Windows. There are other `ps` modules that are more powerful and probably handles this.

**Comment by dbkaplun** [comment]
Would you accept a PR that moves OS-specific data into `win`/`unix` properties?

**Comment by sindresorhus** [comment]
I was hoping to keep this module simple.

https://www.npmjs.com/browse/keyword/ps

**Pull request closed without merging**
