### PR TITLE
Add full process name

### LINKED ISSUE #1: Full process name
[Issuehunt badges](https://issuehunt.io/r/sindresorhus/ps-list/issues/1)

On OS X and Linux the process name is truncated to 15 characters. This is a limitation in `ps` (or rather the kernel).

http://superuser.com/questions/567648/ps-comm-format-always-cuts-the-process-name

Would be nice to somehow be able to return the full process name.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $80.00)

- [issuehunt issuehunt](https://issuehunt.io/u/issuehunt) ($80.00)

### Submitted pull Requests
- [#33 Full executable name *nix](https://issuehunt.io/r/sindresorhus/ps-list/pull/33)
- [#46 Add note regarding using `cmd` and `name` properties](https://issuehunt.io/r/sindresorhus/ps-list/pull/46)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/sindresorhus/ps-list/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

### PR DESCRIPTION
**Pull request by medusalix**
Adds the full process name by splitting the `cmd` column into the `name with args` and the full process `name`. I think this is the least problematic solution because it involves no trickery with `/proc/$pid/exe` and the Unix file system. I also added some tests for it, let me know if you have any suggestions for more cases.

Resolves #1

### CODE REVIEW

**Comment by sindresorhus** [comment]
@stroncium Can you help review this? 🙏

**Comment by sindresorhus** [comment]
@medusalix Some tests are failing.

**Comment by medusalix** [comment]
@sindresorhus Yes, I'm currently working on the failed tests.

**Comment by qti3e** [comment]
@medusalix Hey! I've also got another solution you can check it out, feel free to use it if you want to.
https://gist.github.com/qti3e/9173bb55df41282d2a5da0f3997df5e9

**Comment by medusalix** [comment]
@qti3e Your solution doesn't work for me. It's simply not possible to extract the full process name only from the `comm` and `args` columns. You need to use `cmd` column at the end of the table to prevent the command line from being truncated.

**Comment by stroncium** [comment]
First of all, I must ask if we really want to do that? Because in Linux `comm` is considered process name, and can be changed by process, unlike the path to file process memory was originally mapped from(which might not even exist anymore btw).

**Comment by medusalix** [comment]
@stroncium Yes, that's a very good point, some users of `ps-list` might even rely on the fact that `comm` and not `cmd` is returned. We could maybe keep the old behavior and add a new property (*named something like `cmdline`*) that contains the full command line.

**Comment by sindresorhus** [comment]
We already have a `name` property. How would this be different?

**Comment by medusalix** [comment]
@sindresorhus The `name` property is truncated to 15 characters (a limitation of the kernel as stated in the original issue). This PR uses the `cmd` field (which represents the full command line) and takes the executable path from that. As already mentioned, it might be desirable to add this as a new property to `ps-list` to keep the backwards compatibility.

**Comment by sindresorhus** [comment]
Alright. Let's go with a new property then.

**Comment by medusalix** [comment]
I just realized that PR #30 already replaced the process name in favor of the full executable path (which is not truncated to 15 chars). So I guess there's no way for me to complete this PR...

**Comment by sindresorhus** [comment]
@stroncium Can you confirm that https://github.com/sindresorhus/ps-list/pull/30 fixed #1?

**Comment by stroncium** [comment]
@sindresorhus Not exactly, but I believe it does almost everything we can do about it. More info in #46

**Pull request closed without merging**
