### PR TITLE
Update fastlist to 0.3.0

### LINKED ISSUE #41: Windows 10 support seem to be broken (MSVCP140.dll)
On a fresh installation of Windows 10 the `fastlist.exe` fails to execute with some missing C++ libraries.

Opened upstream issue: https://github.com/MarkTiedemann/fastlist/issues/1

### PR DESCRIPTION
**Pull request by MarkTiedemann**
- Statically include DLLs which are not present in a fresh Windows installation (fixes #41, https://github.com/MarkTiedemann/fastlist/issues/1).
- Reverted packing of the binaries to reduce likelihood of falsely being flagged as a trojan (see #42).

Note that both of these changes increase the size of fastlist from 9kb to 200kb+. The execution speed is still the same, however.

### CODE REVIEW

**Comment by MarkTiedemann** [comment]
@sindresorhus CI is red on Linux. However, I can't check why because I'm unable to view the log. Travis shows me an error message: "_We couldn't display the repository - sindresorhus/ps-list_"

**Comment by sindresorhus** [comment]
> Note that both of these changes increase the size of fastlist from 9kb to 200kb+. The execution speed is still the same, however.

That's fine.

**Comment by MarkTiedemann** [comment]
The failure is unrelated.

Ubuntu, Node 12:

https://travis-ci.com/github/sindresorhus/ps-list/jobs/349742956

```js
{
    // ...
    name: 'node',
    cmd: 'ava'
}
```

Ubuntu, Node 10:

https://travis-ci.com/github/sindresorhus/ps-list/jobs/349742957

```js
{
    // ...
    name: 'ava',
    cmd: 'ava'
}
```

Will make a separate PR with a fix.

**Comment by MarkTiedemann** [comment]
@sindresorhus Once #44 is merged, can you please re-run CI for this PR?

**Comment by MarkTiedemann** [comment]
@sindresorhus CI is now green.

**Pull request merged**
